tap "hashicorp/tap", trusted: true

brew "awscli"
brew "direnv"
brew "fish"
brew "gh"
brew "ghq"
brew "git"
brew "gnu-sed"
brew "go"
brew "graphviz"
brew "grep"
brew "jq"
brew "less"
brew "nano"
brew "peco"
brew "starship"
brew "terminal-notifier"
brew "tokei"
brew "tree"
brew "uv"
brew "hashicorp/tap/terraform"

cask "bruno"
cask "claude"
cask "docker-desktop"
cask "drawio"
cask "figma"
cask "font-udev-gothic"
cask "google-chrome"
cask "jetbrains-toolbox"
cask "logi-options+"
cask "notion"
cask "raycast"
cask "zoom"
