format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$time\
$line_break\
$character"""
add_newline = false

[directory]
truncation_length = 5
truncation_symbol = ".../"

[git_status]
conflicted = "~"
up_to_date = "="

[time]
disabled = false
